POST http://localhost:8080/api/v1/articles/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyYWN6a293c2tpLmJhcnRla0BnbWFpbC5jb20iLCJleHAiOjE3MDEwMzY0NzUsImlhdCI6MTcwMTAwMDQ3NX0.lA0B69bievEXORZ4PkdzMeaiL97C_Pkgx75MD2SUAHM

{
    "title": "title111",
    "content": "content111"
}

###

POST http://localhost:8080/api/v1/articles/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyYWN6a293c2tpLmJhcnRla0BnbWFpbC5jb20iLCJleHAiOjE3MDEwMzY0NzUsImlhdCI6MTcwMTAwMDQ3NX0.lA0B69bievEXORZ4PkdzMeaiL97C_Pkgx75MD2SUAHM

{
  "title": "title222",
  "content": "content222"
}